# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-14 17:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codes',
            name='code',
            field=models.CharField(db_index=True, max_length=64),
        ),
    ]
