# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-15 11:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20170914_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='codes',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Users'),
        ),
        migrations.AlterField(
            model_name='blocklist',
            name='phone_number',
            field=models.CharField(db_index=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='users',
            name='code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Codes'),
        ),
    ]
